# Generated by Django 6.0.2 on 2026-02-12 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, numbers, spaces, and @/./+/-/_ characters.', regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
