# Generated by Django 6.0.2 on 2026-02-16 03:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('inventory', 'Inventory Status'), ('sales', 'Sales & Earnings'), ('orders', 'Order History'), ('activity', 'User Activity')], max_length=50)),
                ('parameters', models.TextField(blank=True, help_text='JSON parameters used for generation')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
