# Generated by Django 6.0.2 on 2026-02-12 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=200)),
                ('farm_size', models.DecimalField(blank=True, decimal_places=2, help_text='Size in acres', max_digits=10, null=True)),
                ('crops_grown', models.TextField(blank=True, help_text='Comma-separated list of crops')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('paddy', 'Paddy/Unhusked Rice'), ('rice', 'Rice'), ('wheat', 'Wheat'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('pulses', 'Pulses'), ('spices', 'Spices'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('bag', 'Bag')], max_length=20)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produce/')),
                ('is_available', models.BooleanField(default=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='farmers.farmerprofile')),
            ],
            options={
                'verbose_name_plural': 'Farm Produce',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_rental', models.BooleanField(default=False)),
                ('rental_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='farmers.farmerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
