# Generated by Django 6.0.2 on 2026-02-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name (e.g., North Field)', max_length=200)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('location', models.CharField(help_text='Village, District', max_length=300)),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy'), ('clay', 'Clay'), ('sandy', 'Sandy'), ('silt', 'Silt'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], max_length=50)),
                ('current_crop', models.CharField(blank=True, help_text='Current crop being grown', max_length=200)),
                ('irrigation_type', models.CharField(choices=[('canal', 'Canal'), ('well', 'Well'), ('borewell', 'Borewell'), ('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler'), ('rainfed', 'Rainfed')], default='rainfed', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the land')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='farmers.farmerprofile')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
                'ordering': ['-created_at'],
            },
        ),
    ]
