# Generated by Django 6.0.2 on 2026-02-18 09:32

import farmers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproduce',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmproduce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=farmers.models.produce_directory_path),
        ),
        migrations.AlterField(
            model_name='farmproduce',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('bag', 'Bag'), ('bunch', 'Bunch'), ('dozen', 'Dozen')], max_length=20),
        ),
    ]
