# Generated by Django 6.0.2 on 2026-02-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmproduce_available_from_farmproduce_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='crops_grown',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_size',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='irrigation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in acres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='main_crops',
            field=models.CharField(blank=True, help_text='Comma-separated list of main crops', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='notif_market',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='notif_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='notif_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
