# Generated by Django 6.0.2 on 2026-02-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_remove_farmerprofile_crops_grown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='main_crops',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='crops_grown',
            field=models.TextField(blank=True, help_text='Comma-separated list of crops'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in acres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='interface_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
