# Generated by Django 6.0.2 on 2026-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='business_license_doc',
            field=models.FileField(blank=True, null=True, upload_to='supplier_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='business_types',
            field=models.CharField(blank=True, help_text='Comma-separated: seeds,fertilizer,manure,equipment_rental', max_length=200),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='supplier_documents/id_proofs/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_documents/shop_images/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
