# Generated by Django 6.0.2 on 2026-02-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='delivery_radius_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='emergency_contact_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='enable_agro_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='enable_equipment_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='enable_fertilizers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='enable_manure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='enable_seeds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='equipment_registration',
            field=models.FileField(blank=True, null=True, upload_to='supplier_documents/equipment/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='supplier_documents/gst/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='home_delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='is_bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='landmark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='notify_low_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='notify_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='notify_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='notify_rentals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='notify_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='pickup_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='subscription_plan',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='taluk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='working_days',
            field=models.CharField(blank=True, help_text='Comma-separated days: Mon,Tue,Wed...', max_length=200),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
